services:
  - type: web
    name: techvaults-academy
    env: node
    plan: free
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm preview --host 0.0.0.0 --port $PORT
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_SUPABASE_URL
        fromDatabase:
          name: supabase
          property: url
      - key: VITE_SUPABASE_ANON_KEY
        fromDatabase:
          name: supabase
          property: anon_key
      - key: VITE_APP_URL
        value: https://techvaults-academy.onrender.com
      - key: VITE_COMPANY_EMAIL
        value: academy@techvaults.com