// This file will be generated by Supabase CLI later
// For now, we'll use a placeholder that matches our schema

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          role: 'admin' | 'student'
          created_at: string
          last_login: string | null
        }
        Insert: {
          id?: string
          email: string
          role: 'admin' | 'student'
          created_at?: string
          last_login?: string | null
        }
        Update: {
          id?: string
          email?: string
          role?: 'admin' | 'student'
          created_at?: string
          last_login?: string | null
        }
      }
      profiles: {
        Row: {
          id: string
          user_id: string
          full_name: string
          phone_number: string | null
          profile_photo_url: string | null
          bio: string | null
          linkedin_url: string | null
          github_url: string | null
          role: 'admin' | 'student'
          registration_status: 'pending' | 'active' | 'completed' | 'inactive'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          full_name: string
          phone_number?: string | null
          profile_photo_url?: string | null
          bio?: string | null
          linkedin_url?: string | null
          github_url?: string | null
          role: 'admin' | 'student'
          registration_status?: 'pending' | 'active' | 'completed' | 'inactive'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          full_name?: string
          phone_number?: string | null
          profile_photo_url?: string | null
          bio?: string | null
          linkedin_url?: string | null
          github_url?: string | null
          role?: 'admin' | 'student'
          registration_status?: 'pending' | 'active' | 'completed' | 'inactive'
          created_at?: string
          updated_at?: string
        }
      }
      announcements: {
        Row: {
          id: number;
          title: string;
          content: string;
          created_at: string;
        }
        Insert: {
          id?: number;
          title: string;
          content: string;
          created_at?: string;
        }
        Update: {
          id?: number;
          title?: string;
          content?: string;
          created_at?: string;
        }
      }
      courses: {
        Row: {
          id: number;
          title: string;
          description: string;
          created_at: string;
        }
        Insert: {
          id?: number;
          title: string;
          description: string;
          created_at?: string;
        }
        Update: {
          id?: number;
          title?: string;
          description?: string;
          created_at?: string;
        }
      }
    }
    Enums: {
      user_role: 'admin' | 'student'
      registration_status: 'pending' | 'active' | 'completed' | 'inactive'
    }
  }
}
